### ISSUE TITLE
Cloud in a bottle with boat causes internal server error and client gets kicked

### ISSUE THREAD

**Issue by iikk-a** [florensie/artifacts-fabric#16]
If you have the cloud in a bottle while in a boat and accidentally press jump, you get disconnected from the server due to an "Internal server error".

The crashing didn't occur when the client took the cloud in a bottle off of their trinket slot and tried again.

Here's some log:

```
[05:09:14] [Server thread/WARN]: Failed to handle packet for /86.13.45.237:60139
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:498) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:219) ~[intermediary-server.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:232) ~[intermediary-server.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking in environment type SERVER
        at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:75) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:185) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:152) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at net.fabricmc.fabric.impl.networking.ClientSidePacketRegistryImpl.toPacket(ClientSidePacketRegistryImpl.java:56) ~[e955ac42-bc51-4452-8cb2-be309f18357f.jar:?]
        at net.fabricmc.fabric.api.network.ClientSidePacketRegistry.sendToServer(ClientSidePacketRegistry.java:70) ~[e955ac42-bc51-4452-8cb2-be309f18357f.jar:?]
        at net.fabricmc.fabric.api.network.ClientSidePacketRegistry.sendToServer(ClientSidePacketRegistry.java:89) ~[e955ac42-bc51-4452-8cb2-be309f18357f.jar:?]
        at net.minecraft.class_1309.handler$zod000$invokeDoubleJump(class_1309.java:11353) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_6007(class_1309.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:566) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2254) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:434) ~[intermediary-server.jar:?]
        ... 9 more
[05:09:14] [Server thread/INFO]: Panther0110 lost connection: Internal server error
```

My apologies if this is not the correct place, but considering it only happens with it, I feel inclined to at least mention it.

**Comment by florensie** [comment]
That's definitely a bug with artifacts, I'll look into it.
