### ISSUE TITLE
Hard crash when config is invalid or corrupted

### ISSUE THREAD

**Issue by Sorrelfur** [florensie/artifacts-fabric#26]
The game was working fine, starting fine and then suddenly it was crashing with this error log:

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 4/18/21 11:07 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'artifacts'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	Suppressed: java.lang.ExceptionInInitializerError
		at me.thonk.croptopia.Croptopia.onInitialize(Croptopia.java:77)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2243/1762088210.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
	Caused by: com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
		at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913)
		at com.google.gson.Gson.fromJson(Gson.java:887)
		at com.google.gson.Gson.fromJson(Gson.java:825)
		at me.thonk.croptopia.config.Options.checkForDefaults(Options.java:47)
		at me.thonk.croptopia.config.Options.<init>(Options.java:41)
		at me.thonk.croptopia.Constants.<clinit>(Constants.java:7)
		... 14 more
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1:                                                                                                                             
	at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:74)
	at me.shedaniel.autoconfig.serializer.Toml4jConfigSerializer.deserialize(Toml4jConfigSerializer.java:73)
	at me.shedaniel.autoconfig.serializer.PartitioningSerializer.deserialize(PartitioningSerializer.java:119)
	at me.shedaniel.autoconfig.serializer.PartitioningSerializer.deserialize(PartitioningSerializer.java:40)
	at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:92)
	at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53)
	at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66)
	at artifacts.Artifacts.onInitialize(Artifacts.java:47)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2243/1762088210.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1:                                                                                                                             
	at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:140)
	at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:107)
	at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:72)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1132150056 bytes (1079 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.13.0+1.16.5
		artifacts: Artifacts 3.2.0+fabric
		autoconfig1u: Auto Config v1 Updated 3.3.1
		blockus: Blockus 2.1.1+1.16.5
		bonappetit: Bon Appétit 0.8.5-3
		bookworm: Bookworm Library 3.1.0
		byg: BYG 1.1.7
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cardinal-components-item: Cardinal Components API (items) 2.7.10
		ce_foodstuffs: Common Expansion: Foodstuffs 1.1.5
		cloth-api: Cloth API 1.5.50
		cloth-armor-api-v1: Cloth Armor API v1 1.5.50
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.50
		cloth-common-events-v1: Cloth Common Events v1 1.5.50
		cloth-config2: Cloth Config v4 4.11.19
		cloth-datagen-api-v1: Cloth Datagen v1 1.5.50
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.50
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.5.50
		cloth-scissors-api-v1: Cloth Scissors API v1 1.5.50
		cloth-utils-v1: Cloth Utils v1 1.5.50
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		craftycuisine: Crafty Cuisine b1.2.1
		croptopia: Croptopia 1.3.1
		dawn: Dawn API 1.8
		dynamicfps: Dynamic FPS 2.0.1
		fabric: Fabric API 0.32.9+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		fallingtree: FallingTree 2.11.0
		fiber: fiber 0.23.0-2
		gentlefawn: GentleFawn 1.1.4-MC1.16.5-fabric
		illuminations: Illuminations 1.4.9
		invisframes: Invisible Frames 2.0.1
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.2+1.16.4
		lithium: Lithium 0.6.4
		minecraft: Minecraft 1.16.5
		mooblooms: Mooblooms 1.4.0
		moreberries: More Berries 1.3.4
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		nookbuild: NookBuild 1.4.0
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		patchouli: Patchouli 1.16.4-50-FABRIC
		phosphor: Phosphor 0.7.1+build.11
		pugh_lib: Pugh Lib 1.1.0
		respawnablepets: Respawnable Pets 1.16.5-2
		roughlyenoughitems: Roughly Enough Items 5.11.202
		roughlyenoughitems-api: REI (API) 5.11.202
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.202
		roughlyenoughitems-runtime: REI (Runtime) 5.11.202
		sakurarosea: Sakura Rosea 1.6.0-MC1.16.3-fabric
		sandwichable: Sandwichable 1.2-beta5
		sodium: Sodium 0.1.0
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.5
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		trinkets: Trinkets 2.6.7
		vafoen: Vanilla Food Enhanced 1.1.1
		vanguard: Vanguard 1.0.5
		veggie_way: The Veggie Way 1.0.41
		waystones: Waystones 1.1.1.1
		yummyfoods: Yummy Foods 1.3
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.11.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by florensie** [comment]
Something is wrong in your config file. Either delete it or open it in a text editor to check what's wrong.

**Comment by Sorrelfur** [comment]
> Something is wrong in your config file. Either delete it or open it in a text editor to check what's wrong.

My config file? With the mod or minecraft in general? Im not good at modding so I'm not sure what a config file is or how to fix it

**Comment by florensie** [comment]
A config file contains the settings of a mod, which you can usually also change through mod menu.

Your minecraft folder should have a folder called `config`, in that folder you can delete the `artifacts` folder. This will create a new config file and reset the settings for artifacts to the defaults.

**Comment by florensie** [comment]
I might make this process automatic in the future somehow.
